# Filename: makefile
# Author: Johannes Pikel
# Date: 2017.02.14
# Description: makefile for the smallsh.c file


CXX = gcc

SRCS = pikelj.smallsh.c

HEADERS = 

CXXFLAGS = -x c
CXXFLAGS += -g
CXXFLAGS += -Wall
CXXFLAGS += -pedantic-errors

main: ${SRCS} ${HEADERS}
	${CXX} ${CXXFLAGS} ${SRCS} -o smallsh


